version: 2.1

executors:
  python_docker:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy

jobs:
  build:
    executor: python_docker
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            ls -al
            sudo chown -R circleci:circleci .
            chmod -R +rwx ./ci
            ./ci/setup.sh
          name: Setup
      - run:
          command: |
            ./ci/run_tests.sh
          name: Run Tests
      - store_artifacts:
          path: reports
      - run:
          command: tar -cvf package.tar .
          name: Create Package
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*.tar

  deploy:
    executor: python_docker
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Content to deploy
          command: ls
      - deploy:
          name: Deploy artifacts
          command: |
              mkdir deploy
              cp package.tar deploy/
      - store_artifacts:
          path: deploy

workflows:
  build_test_deploy:
    jobs:
      - build:
          name: build
      - deploy:
          requires: build
