version: 2.1

executors:
  python_docker:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy

jobs:
  build:
    executor: python_docker
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            ls -al
            sudo chown -R circleci:circleci .
            chmod -R +rwx ./ci
            ./ci/setup.sh
          name: Setup
      - run:
          command: |
            ./ci/run_tests.sh
          name: Run Tests

workflows:
  build_test_deploy:
    jobs:
      - build:
          name: build
