version: 2.1

executors:
  python_docker:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy
                    
jobs:
  build:
    executor: python_docker
      steps:
        - run:
          command: |
              echo 'Hello world, Welcome'

workflows:
  build_test_deploy:
    jobs:
      - build:
            name: build


